ad = input("adınız nedir? \t:")
print(type(ad))
print("Memnun Oldum", ad)
print("Yaşın Kaç?")
yas = int(input())
print(type(yas))
print("ehliyet alacak yaşta mısın", yas >= 18)
print("boyun kaç")
boy = float(input())
print("maşallah")
print("btk akademiyi sevdin mi")
cevap = bool(input())
print("bize olan sevgi durumun", cevap)
print("geldiğin için teşekkürler")