print("adınız nedir?")
ad = input()
print(type(ad))
print("Memnun Oldum", ad)
print("Yaşın Kaç?")
yas = int(input())
print(type(yas))
print("ehliyet alacak yaşta mısın", yas >= 18)
print("boyun kaç")
input()
print("maşallah")
print("btk akademiyi sevdin mi")
input()
print("geldiğin için teşekkürler")