dosya = open("deneme.txt")
# print(dosya.read())
# print(dosya.read(10))
# print(dosya.readline())
# print(dosya.readline())
# satirlar = dosya.readlines()
# print(satirlar)
# for satir in satirlar:
#     print(satir, end="")
okuma1 = dosya.read()
print(okuma1)
okuma2 = dosya.read()
print(okuma2)
dosya.close()